kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: kube-dumper
subjects:
  - kind: ServiceAccount
    namespace: kube-dumper
    name: kube-dumper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-dumper
