apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../dump-files
  - ./clusterRole.yaml
  - ./clusterRoleBinding.yaml
  - ./configMap.yaml
  - ./deployment.yaml
  - ./serviceAccount.yaml
generators:
  - ./aws.secret.yaml
  - ./ssh.secret.yaml
